language: node_js
sudo: required
jdk: oraclejdk8
dist: trusty
addons:
  chrome: stable
  firefox: stable
  apt:
    packages:
      - oracle-java8-set-default
before_script:
  - npm run compile
before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 selenium/standalone-chrome
script:
  - npm test
  - npm run danger
branches:
  only:
    - master
cache:
  directories:
    - node_modules
